[package]
name = "ao-audio"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ao-rdb.workspace = true
ao-formats.workspace = true
cpal = "0.15"
symphonia = { version = "0.5", default-features = false, features = ["wav", "ogg", "vorbis", "mp3", "pcm", "adpcm"] }
